import {
  LayoutDashboard,
  Users,
  UserRound,
  Bot,
  MessageSquare,
  Sparkles,
  BarChart3,
  Settings,
  Share2,
  Radio,
  Inbox as InboxIcon,
  HardDrive,
  Zap,
  Target,
  PieChart,
  LineChart,
  Tag,
  ClipboardCheck,
  Database,
  ListFilter,
  Briefcase,
  ShieldCheck,
  Building2,
  Workflow,
  Store,
  FolderKanban,
  Megaphone,
  Clock,
  Trash2,
  MessageCircle,
} from 'lucide-react';
import { NavModule } from '@shared/types/nav';

export const NAV_MODULES: NavModule[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    match: '/dashboard',
    to: '/dashboard/home',
    description: 'Vista general de tu negocio.',
    color: 'text-primary',
    children: [
      {
        to: '/dashboard/home',
        label: 'Inicio',
        icon: LayoutDashboard,
        description: 'Vista general e inicio.',
      },
    ],
  },
  {
    key: 'crm',
    label: 'CRM',
    icon: Users,
    match: '/crm',
    to: '/crm/contacts',
    description: 'Gestiona tu cartera de leads y clientes.',
    color: 'text-primary',
    children: [
      {
        to: '/crm/contacts',
        label: 'Contactos',
        icon: UserRound,
        description: 'Listado y gestión de contactos.',
      },
      {
        to: '/crm/leads',
        label: 'Inbox Leads',
        icon: InboxIcon,
        description: 'Todos los leads entrantes.',
      },
      {
        to: '/crm/companies',
        label: 'Empresas',
        icon: Building2,
        description: 'Gestiona empresas y organizaciones.',
      },
      {
        to: '/crm/deals',
        label: 'Negocios',
        icon: Briefcase,
        description: 'Pipeline de ventas y tratos.',
      },
      {
        to: '/crm/tags',
        label: 'Etiquetas',
        icon: Tag,
        description: 'Categoriza tus contactos.',
      },
      {
        to: '/crm/tasks',
        label: 'Tareas',
        icon: ClipboardCheck,
        description: 'Seguimiento de actividades.',
      },
      {
        to: '/crm/fields',
        label: 'Campos',
        icon: Database,
        description: 'Personaliza tus datos.',
      },
      {
        to: '/crm/segments',
        label: 'Segmentos',
        icon: ListFilter,
        description: 'Listas inteligentes de leads.',
      },
    ],
  },
  {
    key: 'agents',
    label: 'Marketing',
    icon: Megaphone,
    match: '/agents',
    to: '/agents/store',
    description: 'Tus agentes de IA trabajando para alcanzar tus objetivos.',
    color: 'text-secondary',
    children: [
      {
        to: '/agents/projects',
        label: 'Proyectos',
        icon: FolderKanban,
        description: 'Gestiona tus proyectos de marketing.',
      },
      {
        to: '/agents/team',
        label: 'Equipo de Agentes',
        icon: Bot,
        description: 'Gestiona tu equipo de agentes.',
      },
      {
        to: '/agents/chat',
        label: 'Chat con el Equipo',
        icon: MessageCircle,
        description: 'Habla con tu equipo de agentes y definí tus objetivos.',
      },
      {
        to: '/agents/store',
        label: 'Catálogo de Agentes',
        icon: Store,
        description: 'Catálogo de agentes de IA disponibles.',
      },
    ],
  },
  {
    key: 'automations',
    label: 'Workflows',
    icon: Workflow,
    match: '/automations',
    to: '/automations/workflows',
    description: 'Crea y gestiona flujos de trabajo y agentes automatizados.',
    color: 'text-secondary',
    children: [
      {
        to: '/automations/workflows',
        label: 'Workflows',
        icon: Workflow,
        description: 'Diseña flujos de automatización visual.',
      },
      {
        to: '/automations/agents',
        label: 'Agentes de Flujo',
        icon: Bot,
        description: 'Configura agentes automatizados.',
      },
    ],
  },
  {
    key: 'inbox',
    label: 'Inbox',
    icon: InboxIcon,
    match: '/inbox',
    to: '/inbox',
    description: 'Gestiona todas tus conversaciones en un solo lugar.',
    color: 'text-accent',
    children: [
      {
        to: '/inbox',
        label: 'Conversaciones',
        icon: MessageSquare,
        description: 'Chats en tiempo real.',
      },
      {
        to: '/inbox/automations',
        label: 'Respuestas rápidas',
        icon: Zap,
        description: 'Automatiza tus respuestas.',
      },
      {
        to: '/inbox/channels',
        label: 'Canales',
        icon: Share2,
        description: 'Catálogo y gestión de canales.',
        menuKey: 'inbox_channels',
      },
      {
        to: '/inbox/my-channels',
        label: 'Mis Canales',
        icon: Radio,
        description: 'Canales conectados a tu negocio.',
        menuKey: 'inbox_my_channels',
      },
    ],
  },
  {
    key: 'drive',
    label: 'Drive',
    icon: HardDrive,
    match: '/drive',
    to: '/drive/me',
    description: 'Administra los archivos y recursos de tu negocio.',
    color: 'text-primary',
    children: [
      {
        to: '/drive/me',
        label: 'Mi unidad',
        icon: HardDrive,
        description: 'Tus archivos y carpetas personales.',
      },
      {
        to: '/drive/company',
        label: 'Empresa',
        icon: Building2,
        description: 'Archivos y carpetas compartidos del negocio.',
      },
      {
        to: '/drive/recent',
        label: 'Recientes',
        icon: Clock,
        description: 'Archivos abiertos o modificados recientemente.',
      },
      {
        to: '/drive/trash',
        label: 'Papelera',
        icon: Trash2,
        description: 'Archivos y carpetas eliminados.',
      },
    ],
  },
  {
    key: 'analytics',
    label: 'Analytics',
    icon: BarChart3,
    match: '/analytics',
    to: '/analytics/general',
    description: 'Métricas y reportes profundos de tu negocio.',
    color: 'text-info',
    children: [
      {
        to: '/analytics/general',
        label: 'General',
        icon: PieChart,
        description: 'Vista global del negocio.',
      },
      {
        to: '/analytics/conversations',
        label: 'Conversaciones',
        icon: MessageSquare,
        description: 'Rendimiento del chat.',
      },
      {
        to: '/analytics/leads',
        label: 'Leads',
        icon: Target,
        description: 'Tasa de conversión.',
      },
      {
        to: '/analytics/performance',
        label: 'Rendimiento',
        icon: LineChart,
        description: 'Eficiencia de agentes.',
      },
    ],
  },
  {
    key: 'settings',
    label: 'Settings',
    icon: Settings,
    match: '/settings',
    to: '/settings/configuracion',
    description: 'Configura tu cuenta y preferencias.',
    color: 'text-primary',
    children: [
      {
        type: 'group' as const,
        key: 'settings_general',
        label: 'Ajustes generales',
        icon: Settings,
        description: 'Ajustes generales de la cuenta y plataforma.',
        children: [
          { to: '/settings/my-account', label: 'Mi cuenta', icon: UserRound },
          { to: '/settings/my-company', label: 'Mi empresa', icon: Building2 },
          { to: '/settings/plans', label: 'Planes', icon: Zap },
        ],
      },
      {
        type: 'group' as const,
        key: 'settings_team_access',
        label: 'Equipo y accesos',
        icon: Users,
        description: 'Gestión de usuarios, equipos y permisos de acceso.',
        children: [
          { to: '/settings/users', label: 'Usuarios', icon: UserRound },
          { to: '/settings/teams', label: 'Equipo', icon: Users },
          { to: '/settings/roles', label: 'Permisos', icon: ShieldCheck },
        ],
      },
      {
        type: 'group' as const,
        key: 'settings_business',
        label: 'Configuración del negocio',
        icon: Building2,
        description: 'Configuraciones específicas del negocio: ciclo de vida.',
        children: [
          {
            to: '/settings/configuracion',
            label: 'Configuración',
            icon: Settings,
          },
          { to: '/settings/lifecycle', label: 'Ciclo de vida', icon: Sparkles },
        ],
      },
    ],
  },
];
