import {
  LayoutDashboard,
  Users,
  UserRound,
  Bot,
  Code,
  MessageSquare,
  Sparkles,
  BarChart3,
  Settings,
  TrendingUp,
  Search,
  Share2,
  Inbox as InboxIcon,
  Filter,
  Zap,
  Layout,
  Target,
  BookOpen,
  Mic,
  Brain,
  PieChart,
  LineChart,
  Tag,
  ClipboardCheck,
  Database,
  ListFilter,
  Briefcase,
  ShieldCheck,
  Building2,
} from 'lucide-react';
import { NavModule } from '@shared/types/nav';

export const NAV_MODULES: NavModule[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    match: '/dashboard',
    to: '/dashboard/home',
    description: 'Vista general de tu negocio.',
    color: 'text-primary',
    children: [
      {
        to: '/dashboard/home',
        label: 'Inicio',
        icon: LayoutDashboard,
        description: 'Vista general e inicio.',
      },
    ],
  },
  {
    key: 'crm',
    label: 'CRM',
    icon: Users,
    match: '/crm',
    to: '/crm/contacts',
    description: 'Gestiona tu cartera de leads y clientes.',
    color: 'text-primary',
    children: [
      {
        to: '/crm/contacts',
        label: 'Contactos',
        icon: UserRound,
        description: 'Listado y gestión de contactos.',
      },
      {
        to: '/crm/leads',
        label: 'Inbox Leads',
        icon: InboxIcon,
        description: 'Todos los leads entrantes.',
      },
      {
        to: '/crm/companies',
        label: 'Empresas',
        icon: Building2,
        description: 'Gestiona empresas y organizaciones.',
      },
      {
        to: '/crm/deals',
        label: 'Negocios',
        icon: Briefcase,
        description: 'Pipeline de ventas y tratos.',
      },
      {
        to: '/crm/tags',
        label: 'Etiquetas',
        icon: Tag,
        description: 'Categoriza tus contactos.',
      },
      {
        to: '/crm/tasks',
        label: 'Tareas',
        icon: ClipboardCheck,
        description: 'Seguimiento de actividades.',
      },
      {
        to: '/crm/fields',
        label: 'Campos',
        icon: Database,
        description: 'Personaliza tus datos.',
      },
      {
        to: '/crm/segments',
        label: 'Segmentos',
        icon: ListFilter,
        description: 'Listas inteligentes de leads.',
      },
    ],
  },
  {
    key: 'agents',
    label: 'Agentes IA',
    icon: Sparkles,
    match: '/agents',
    to: '/agents/strategy',
    description: 'Lanza equipos de IA para crear contenido y análisis.',
    color: 'text-secondary',
    children: [
      {
        to: '/agents/strategy',
        label: 'Estrategia',
        icon: TrendingUp,
        description: 'Optimización de marca.',
      },
      {
        to: '/agents/content',
        label: 'Contenido',
        icon: MessageSquare,
        description: 'Creación de textos y contenidos.',
      },
      {
        to: '/agents/analysis',
        label: 'Análisis',
        icon: Search,
        description: 'Insights de negocio.',
      },
    ],
  },
  {
    key: 'inbox',
    label: 'Inbox',
    icon: InboxIcon,
    match: '/inbox',
    to: '/inbox',
    description: 'Gestiona todas tus conversaciones en un solo lugar.',
    color: 'text-accent',
    children: [
      {
        to: '/inbox',
        label: 'Conversaciones',
        icon: MessageSquare,
        description: 'Chats en tiempo real.',
      },
      {
        to: '/inbox/automations',
        label: 'Respuestas rápidas',
        icon: Zap,
        description: 'Automatiza tus respuestas.',
      },
      {
        to: '/inbox/channels',
        label: 'Canales',
        icon: Share2,
        description: 'WhatsApp, Messenger, Web.',
      },
    ],
  },
  {
    key: 'funnels',
    label: 'Embudos',
    icon: Filter,
    match: '/funnels',
    to: '/funnels/dashboard',
    description: 'Convierte visitas en clientes con flujos optimizados.',
    color: 'text-primary',
    children: [
      {
        to: '/funnels/dashboard',
        label: 'Dashboard',
        icon: LayoutDashboard,
        description: 'Vista general del funnel.',
      },
      {
        to: '/funnels/builder',
        label: 'Constructor',
        icon: Layout,
        description: 'Diseña tus flujos de venta.',
      },
      {
        to: '/funnels/templates',
        label: 'Plantillas',
        icon: Code,
        description: 'Modelos listos para usar.',
      },
      {
        to: '/funnels/automations',
        label: 'Automatizaciones',
        icon: Zap,
        description: 'Reglas y disparadores.',
      },
      {
        to: '/funnels/leads',
        label: 'Leads',
        icon: Target,
        description: 'Prospectos generados.',
      },
      {
        to: '/funnels/analytics',
        label: 'Analítica',
        icon: BarChart3,
        description: 'Rendimiento de conversión.',
      },
    ],
  },
  {
    key: 'avatar',
    label: 'Avatar',
    icon: Bot,
    match: '/avatar',
    to: '/avatar/identity',
    description: 'Define la personalidad y conocimiento de tu IA.',
    color: 'text-secondary',
    children: [
      {
        to: '/avatar/identity',
        label: 'Identidad',
        icon: UserRound,
        description: 'Personalidad y tono de voz.',
      },
      {
        to: '/avatar/knowledge',
        label: 'Conocimiento',
        icon: BookOpen,
        description: 'Entrenamiento y documentos.',
      },
      {
        to: '/avatar/voice',
        label: 'Voz',
        icon: Mic,
        description: 'Configuración de audio e IA.',
      },
      {
        to: '/avatar/memory',
        label: 'Memoria',
        icon: Brain,
        description: 'Contexto y aprendizaje.',
      },
    ],
  },
  {
    key: 'analytics',
    label: 'Analítica',
    icon: BarChart3,
    match: '/analytics',
    to: '/analytics/general',
    description: 'Métricas y reportes profundos de tu negocio.',
    color: 'text-info',
    children: [
      {
        to: '/analytics/general',
        label: 'General',
        icon: PieChart,
        description: 'Vista global del negocio.',
      },
      {
        to: '/analytics/conversations',
        label: 'Conversaciones',
        icon: MessageSquare,
        description: 'Rendimiento del chat.',
      },
      {
        to: '/analytics/leads',
        label: 'Leads',
        icon: Target,
        description: 'Tasa de conversión.',
      },
      {
        to: '/analytics/performance',
        label: 'Rendimiento',
        icon: LineChart,
        description: 'Eficiencia de agentes.',
      },
    ],
  },
  {
    key: 'settings',
    label: 'Configuración',
    icon: Settings,
    match: '/settings',
    to: '/settings/configuracion',
    description: 'Configura tu cuenta y preferencias.',
    color: 'text-primary',
    children: [
      {
        type: 'group' as const,
        key: 'settings_general',
        label: 'Ajustes generales',
        icon: Settings,
        description: 'Ajustes generales de la cuenta y plataforma.',
        children: [
          {
            to: '/settings/configuracion',
            label: 'Configuración',
            icon: Settings,
          },
          { to: '/settings/my-account', label: 'Mi cuenta', icon: UserRound },
          { to: '/settings/my-company', label: 'Mi empresa', icon: Building2 },
          { to: '/settings/plans', label: 'Planes', icon: Zap },
        ],
      },
      {
        type: 'group' as const,
        key: 'settings_team_access',
        label: 'Equipo y accesos',
        icon: Users,
        description: 'Gestión de usuarios, equipos y permisos de acceso.',
        children: [
          { to: '/settings/users', label: 'Usuarios', icon: UserRound },
          { to: '/settings/teams', label: 'Equipo', icon: Users },
          { to: '/settings/roles', label: 'Permisos', icon: ShieldCheck },
        ],
      },
      {
        type: 'group' as const,
        key: 'settings_business',
        label: 'Configuración del negocio',
        icon: Building2,
        description:
          'Configuraciones específicas del negocio: ciclo de vida y canales.',
        children: [
          { to: '/settings/lifecycle', label: 'Ciclo de vida', icon: Sparkles },
          { to: '/settings/channels', label: 'Canales', icon: Share2 },
          { to: '/settings/agents', label: 'Agentes', icon: Bot },
        ],
      },
    ],
  },
];
